#!/usr/bin/python
# -*- coding: UTF-8 -*-

print "hello";
print "你好";

# “#”为注释

# 标识符由字母、数字、下划线组成，不能以数字开头，区分大小写

# 用缩进表示模块，而不是{}
if 1:
	print "Ture1"
	print "Ture2"  #严格按照缩进
else:
	print "false1"
	print "false2"

		
#使用引号( ' )、双引号( " )、三引号( ''' 或 """ ) 来表示字符串,三引号可以由多行组成
word = 'word'
sentence = "这是一个句子。"
paragraph = """这是一个段落。
包含了多个语句"""    
print word,sentence,paragraph  # 不换行输出
print word
print sentence
print paragraph


#Python 中的变量赋值不需要类型声明
x = 100
y = 100.1

total = x + \
        y  #用\将一行语句分为多行
print total

#多个变量赋值
a ,b ,c = 1, 2.1, 'join'
print a,b,c

#字符串
print "************字符串"
print c[1:3] #输出字符串中第2个到第5个之间的字符串
print c * 2  #字符串输出两次
print c + "test" #输出连接的字符串

#列表[]. 支持字符，数字，字符串甚至可以包含列表（即嵌套）.
print "************列表"
list = ['runoob', 1, 2.1, 'join', 40.2]
tinylist = [123, 'join']
print list
print list[0]
print list[1:3]
print list [2:]
print tinylist * 2
print list + tinylist
list[0] = 111
print list

#元组（类似list），不能二次赋值，相当于只读list
print "************元组"
tuple = ('runoob', 1, 2.1, 'join', 40.2)
tinytuple = (123, 'join')
print tuple
print tuple + tinytuple

#字典{},由索引(key)和它对应的值value组成,是无序的对象集合。
print "************字典"
dict = {}
dict['one'] = 'this is one'
dict[2] = 'this is two'
tinydict = {'name':'join', 'code':'22', 'dept':'sales'}
print dict
print dict['one']          # 输出键为'one' 的值
print dict[2]              # 输出键为 2 的值
print tinydict             # 输出完整的字典
print tinydict.keys()      # 输出所有键
print tinydict.values()    # 输出所有值





