#!/usr/bin/python
# -*- coding: UTF-8 -*-

#  len()返回对象（字符、列表、元组等）长度或项目个数
#  pop()移除列表中最后一个元素，并返回该元素的值
#  append()在列表尾部添加新对象。。以上均为内置函数

#  del为内置关键字（如import、return等），删除一个对象（list、变量、类的实例等）


print "##############列表"   # []
list1 = ['physic', 'chemistry', 1992, 2000]
list2 = [1, 2, 3, 4, 5, 6]

a = list1.pop();
list2.append(a)
print list1
print list2
print list2[-2]

del list2[2]
print list2
print 'len(list1+list2)=',len(list1+list2)

print 'list2  max=',max(list2), 'min=',min(list2), 'cmp(list1,list2)=',cmp(list1,list2)
print '\n'
print "list1=",list1
print "list2=",list2
print list1+list2
print list1 * 2
print 2 in list2
for x in list1:
	print x

	print '\n'	
print list1.count(2)  #count()：统计某个元素在list中出现的次数
list1.extend(list2)  #extend():在列表末尾一次性追加另一个序列中的多个值
print "list1=",list1   
print list2.index(2000)  #index():在列表中找出某个值第一个匹配项的索引位置

list1.insert(2,'hello')  #insert():将对象插入列表中
print list1

list1.remove(1992)  #remove():移除列表中某个值的第一个匹配项
print list1

list2.reverse()   #reverse():反向列表中的元素
print list2

list2.sort()  #sort():对列表进行从小到大排序
print list2

print '\n\n\n'
print "##############元组"  # () 与列表类似，但值不可改
print ('all'),('all',)  #如果元组只有1个元素，就必须加一个逗号，防止被当作括号运算
print tuple(list1)  #tuple():将列表转换为元组
print list( tuple(list1) )  #list():将元组转换为列表



print '\n\n\n'
print "##############字典"  #{key1 : value1, key2 : value2 , ...}  key必须不同，且不可变（所以list不能做key）
dict = {'Name': 'Zara', 'Age': 7, 'Class': 'First'};
dict['Age'] = 8   #修改字典
dict['School'] = 'DPS School'  #增加对象
print dict

test1 = dict.pop('School')  # pop():删除字典给定键 key 所对应的值，返回值为被删除的value
print 'pop:',test1,dict

test2 = dict.popitem() #popitem():随机返回并删除字典中的一对键和值
print 'popitem:',test2,dict

print len(dict)
print str(dict)   #输出字典可打印的字符串表示
print type(dict)  #返回输入的变量类型，如果变量是字典就返回字典类型

del dict['Name']  #删除对象
print dict
dict.clear()   #情况字典
print dict
del dict   #删除字典

dict1 = {'user':'runoob','num':[1,2,3]}
dict2 = dict1  # 浅拷贝: 引用对象
dict3 = dict1.copy()  # 深拷贝：不会随dict1 修改而修改

dict1['user']='root'
dict1['num'].remove(1)  #修改dict1的值

print 'dict1=',dict1, 'dict2=',dict2, 'dict3=',dict3

for a,b in dict1.items():   #items():以列表返回可遍历的(键, 值) 元组数组
	print a,b

print dict1.keys()  #keys():以列表返回一个字典所有的键

dict3 = {'Name': 'Zara', 'Age': 7}
dict1.update(dict3)  #update():把字典dict3的键/值对更新到dict里。
print dict1