#!/usr/bin/python
# -*- coding: UTF-8 -*-

# GUI编程(Tkinter) 图形界面
# Tkinter   wxPython   Jython

#不能再xshell上运行，因为xshell不支持图形
#在ubuntu的终端上运行：搜索计算机->Terminal

def func1():
	import Tkinter # 导入 Tkinter 库
	top = Tkinter.Tk() #创建控件,指定这个控件的 master， 即这个控件属于哪一个
	top.mainloop() #告诉 GM(geometry manager) 有一个控件产生了,会产生一个窗口
#func1()

def func2():
	from Tkinter import *  # 导入 Tkinter 库
	root = Tk()  # 创建窗口对象的背景色
	li = ['C','python','php','html','SQL','java']
	movie = ['CSS','jQuery','Bootstrap']
	listb  = Listbox(root)    #  创建两个列表组件
	listb2 = Listbox(root)
	
	for item in li:   # 第一个小部件插入数据
		listb.insert(0,item)
	for item in movie:
		listb2.insert(0,item)
	
	listb.pack() # 将小部件放置到主窗口中
	listb2.pack()
	root.mainloop()# 进入消息循环
#func2()

'''
Tkinter 控件:
Button        按钮控件；在程序中显示按钮。
Canvas        画布控件；显示图形元素如线条或文本
Checkbutton   多选框控件；用于在程序中提供多项选择框
Entry         输入控件；用于显示简单的文本内容
Frame         框架控件；在屏幕上显示一个矩形区域，多用来作为容器
Label         标签控件；可以显示文本和位图
Listbox       列表框控件；在Listbox窗口小部件是用来显示一个字符串列表给用户
Menubutton    菜单按钮控件，由于显示菜单项。
Menu          菜单控件；显示菜单栏,下拉菜单和弹出菜单
Message       消息控件；用来显示多行文本，与label比较类似
Radiobutton   单选按钮控件；显示一个单选的按钮状态
Scale         范围控件；显示一个数值刻度，为输出限定范围的数字区间
Scrollbar     滚动条控件，当内容超过可视化区域时使用，如列表框。.
Text          文本控件；用于显示多行文本
Toplevel      容器控件；用来提供一个单独的对话框，和Frame比较类似
Spinbox       输入控件；与Entry类似，但是可以指定输入范围值
PanedWindow   是一个窗口布局管理的插件，可以包含一个或者多个子控件。
LabelFrame    是一个简单的容器控件。常用与复杂的窗口布局。
tkMessageBox  用于显示你应用程序的消息框。

所有控件的共同属性:
Dimension     控件大小；
Color         控件颜色；
Font          控件字体；
Anchor        锚点；
Relief        控件样式；
Bitmap        位图；
Cursor        光标；

几何管理,管理整个控件区域组织:
pack()        包装；
grid()        网格；
place()       位置；
'''

#画图，学用circle画圆形
def func3():
	from Tkinter import *
	canvas = Canvas(width=300, height=200, bg='yellow')
	canvas.pack()
	canvas.create_oval(40,40,100,100, fill='pink') # 圆形 在矩形(40,40)->(100,100)内画圆
	canvas.create_oval(120,120,100,70, fill='red') # 椭圆形
	canvas.create_line(200,200,150,150, width=5, fill='green') #直线(200，200)->(150，150)
	canvas.create_rectangle(150,80,200,130,fill='pink')
	mainloop()
#rectangle(int left, int top, int right, int bottom) (left ，top )为矩形的左上坐标，(right,bottom)为矩形的右下坐标，两者可确定一个矩形的大小
#func3()
